#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Millionlights
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.ComponentModel.DataAnnotations.Schema;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MillionLightDb")]
	public partial class MillionlightsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MillionlightsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MillionLightDbConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MillionlightsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MillionlightsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MillionlightsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MillionlightsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BatchExecuteUserData")]
		public ISingleResult<BatchExecuteUserDataResult> BatchExecuteUserData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<BatchExecuteUserDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUsersEmailAndSMS")]
		public ISingleResult<GetUsersEmailAndSMSResult> GetUsersEmailAndSMS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsEmail", DbType="VarChar(50)")] string isEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NotificationStatusId", DbType="Int")] System.Nullable<int> notificationStatusId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate, isEmail, notificationStatusId);
			return ((ISingleResult<GetUsersEmailAndSMSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUserDetails")]
		public ISingleResult<GetUserDetailsResult> GetUserDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Role", DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(50)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartnerId", DbType="Int")] System.Nullable<int> partnerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), role, startDate, endDate, city, state, country, partnerId);
			return ((ISingleResult<GetUserDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUserDetailsForView")]
		public ISingleResult<GetUserDetailsForViewResult> GetUserDetailsForView([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Role", DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(50)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartnerId", DbType="Int")] System.Nullable<int> partnerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), role, startDate, endDate, city, state, country, partnerId);
			return ((ISingleResult<GetUserDetailsForViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertToUserCourses")]
		public ISingleResult<InsertToUserCoursesResult> InsertToUserCourses()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<InsertToUserCoursesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReseedIdentityOfUsersTable")]
		public int ReseedIdentityOfUsersTable()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.GetAllCourseDetails")]
        public ISingleResult<GetAllCourseDetailsResult> GetAllCourseDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Id", DbType = "VarChar(100)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "MinPrice", DbType = "Int")] System.Nullable<int> minPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "MaxPrice", DbType = "Int")] System.Nullable<int> maxPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "NVarChar(MAX)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "NVarChar(MAX)")] string courseName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> page)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, minPrice, maxPrice, type, courseName, page);
            return ((ISingleResult<GetAllCourseDetailsResult>)(result.ReturnValue));
        }
		
	}
	
	public partial class BatchExecuteUserDataResult
	{
		
		private int _UserId;
		
		private string _UserName;
		
		private string _EmailId;
		
		private string _Password;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber;
		
		public BatchExecuteUserDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(MAX)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
	}
	
	public partial class GetUsersEmailAndSMSResult
	{
		
		private int _Id;
		
		private int _Receiver;
		
		private string _ReceiverName;
		
		private string _Sender;
		
		private string _Subject;
		
		private string _Message;
		
		private System.DateTime _DateSent;
		
		private bool _IsRead;
		
		private System.Nullable<System.DateTime> _ReadDate;
		
		private bool _IsAlert;
		
		private System.Nullable<System.DateTime> _SMSDate;
		
		private System.Nullable<System.DateTime> _MailDate;
		
		private string _EMAILFormattedDate;
		
		private string _SMSFormattedDate;
		
		private System.Nullable<int> _NotificationStatusId;
		
		public GetUsersEmailAndSMSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receiver", DbType="Int NOT NULL")]
		public int Receiver
		{
			get
			{
				return this._Receiver;
			}
			set
			{
				if ((this._Receiver != value))
				{
					this._Receiver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverName", DbType="NVarChar(MAX)")]
		public string ReceiverName
		{
			get
			{
				return this._ReceiverName;
			}
			set
			{
				if ((this._ReceiverName != value))
				{
					this._ReceiverName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="NVarChar(MAX)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this._Sender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(MAX)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateSent", DbType="DateTime NOT NULL")]
		public System.DateTime DateSent
		{
			get
			{
				return this._DateSent;
			}
			set
			{
				if ((this._DateSent != value))
				{
					this._DateSent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRead", DbType="Bit NOT NULL")]
		public bool IsRead
		{
			get
			{
				return this._IsRead;
			}
			set
			{
				if ((this._IsRead != value))
				{
					this._IsRead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this._ReadDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAlert", DbType="Bit NOT NULL")]
		public bool IsAlert
		{
			get
			{
				return this._IsAlert;
			}
			set
			{
				if ((this._IsAlert != value))
				{
					this._IsAlert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SMSDate
		{
			get
			{
				return this._SMSDate;
			}
			set
			{
				if ((this._SMSDate != value))
				{
					this._SMSDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> MailDate
		{
			get
			{
				return this._MailDate;
			}
			set
			{
				if ((this._MailDate != value))
				{
					this._MailDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILFormattedDate", DbType="VarChar(30)")]
		public string EMAILFormattedDate
		{
			get
			{
				return this._EMAILFormattedDate;
			}
			set
			{
				if ((this._EMAILFormattedDate != value))
				{
					this._EMAILFormattedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSFormattedDate", DbType="VarChar(30)")]
		public string SMSFormattedDate
		{
			get
			{
				return this._SMSFormattedDate;
			}
			set
			{
				if ((this._SMSFormattedDate != value))
				{
					this._SMSFormattedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotificationStatusId", DbType="Int")]
		public System.Nullable<int> NotificationStatusId
		{
			get
			{
				return this._NotificationStatusId;
			}
			set
			{
				if ((this._NotificationStatusId != value))
				{
					this._NotificationStatusId = value;
				}
			}
		}
	}
	
	public partial class GetUserDetailsResult
	{
		
		private int _PartnerId;
		
		private int _UserDetailsId;
		
		private int _UserId;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _FullName;
		
		private string _EmailId;
		
		private System.Nullable<long> _PhoneNumber;
		
		private string _City;
		
		private string _Country;
		
		private string _State;
		
		private string _RoleName;
		
		private System.DateTime _RegisteredDatetime;
		
		private string _RegisteredDatetimeString;
		
		private string _Name;
		
		private bool _IsActive;
		
		public GetUserDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartnerId", DbType="Int NOT NULL")]
		public int PartnerId
		{
			get
			{
				return this._PartnerId;
			}
			set
			{
				if ((this._PartnerId != value))
				{
					this._PartnerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserDetailsId", DbType="Int NOT NULL")]
		public int UserDetailsId
		{
			get
			{
				return this._UserDetailsId;
			}
			set
			{
				if ((this._UserDetailsId != value))
				{
					this._UserDetailsId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(MAX)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="BigInt")]
		public System.Nullable<long> PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(MAX)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(MAX)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredDatetime", DbType="DateTime NOT NULL")]
		public System.DateTime RegisteredDatetime
		{
			get
			{
				return this._RegisteredDatetime;
			}
			set
			{
				if ((this._RegisteredDatetime != value))
				{
					this._RegisteredDatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredDatetimeString", DbType="VarChar(19)")]
		public string RegisteredDatetimeString
		{
			get
			{
				return this._RegisteredDatetimeString;
			}
			set
			{
				if ((this._RegisteredDatetimeString != value))
				{
					this._RegisteredDatetimeString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
	
	public partial class GetUserDetailsForViewResult
	{
		
		private int _PartnerId;
		
		private int _UserDetailsId;
		
		private int _UserId;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _FullName;
		
		private string _EmailId;
		
		private System.Nullable<long> _PhoneNumber;
		
		private string _City;
		
		private string _Country;
		
		private string _State;
		
		private string _RoleName;
		
		private System.DateTime _RegisteredDatetime;
		
		private string _RegisteredDatetimeString;
		
		private string _Name;
		
		private bool _IsActive;
		
		public GetUserDetailsForViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartnerId", DbType="Int NOT NULL")]
		public int PartnerId
		{
			get
			{
				return this._PartnerId;
			}
			set
			{
				if ((this._PartnerId != value))
				{
					this._PartnerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserDetailsId", DbType="Int NOT NULL")]
		public int UserDetailsId
		{
			get
			{
				return this._UserDetailsId;
			}
			set
			{
				if ((this._UserDetailsId != value))
				{
					this._UserDetailsId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(MAX)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="BigInt")]
		public System.Nullable<long> PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(MAX)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(MAX)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredDatetime", DbType="DateTime NOT NULL")]
		public System.DateTime RegisteredDatetime
		{
			get
			{
				return this._RegisteredDatetime;
			}
			set
			{
				if ((this._RegisteredDatetime != value))
				{
					this._RegisteredDatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredDatetimeString", DbType="VarChar(19)")]
		public string RegisteredDatetimeString
		{
			get
			{
				return this._RegisteredDatetimeString;
			}
			set
			{
				if ((this._RegisteredDatetimeString != value))
				{
					this._RegisteredDatetimeString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
	
	public partial class InsertToUserCoursesResult
	{
		
		private int _UserId;
		
		private string _UserName;
		
		private string _EmailId;
		
		private string _Password;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<long> _PhoneNumber;
		
		public InsertToUserCoursesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="BigInt")]
		public System.Nullable<long> PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
	}
    public partial class GetAllCourseDetailsResult
    {



        private int _Id;



        private string _CourseCode;



        private string _CourseName;



        private string _ShortDescription;



        private string _LongDescription;



        private string _Objective;



        private string _ExamObjective;



        private string _EDXCourseLink;



        private System.Nullable<System.DateTime> _StartDate;



        private System.Nullable<System.DateTime> _EndDate;



        private System.DateTime _CreatedOn;



        private int _CreatedBy;



        private System.DateTime _ModifiedOn;



        private int _ModifiedBy;



        private string _CourseImageLink;



        private System.Nullable<int> _CertificationId;



        private decimal _BasePrice;



        private string _LMSCourseId;



        private bool _EnableForLMS;



        private bool _EnableForCertification;



        private bool _EnableForPayment;



        private string _Duration;



        private int _Hours;



        private int _NoOfSessions;



        private int _CourseAvailability;



        private string _CourseCategory;



        private int _CourseLevels;



        private int _CourseLanguage;



        private int _CourseTypes;



        private bool _HasSampleContents;



        private string _SampleContentsLink;



        private int _CreditPoints;



        private System.Nullable<int> _CertificationProvider;



        private System.Nullable<int> _ExamManager;



        private System.Nullable<int> _CourseProvider;



        private bool _HasVideoLink;



        private string _VideoLink;



        private bool _ScheduleApplicable;



        private int _DeliveryID;



        private string _Instructor;



        private string _Rating;



        private bool _DisplayOnHomePage;



        private bool _IsActive;



        private bool _EvidenceRequired;



        private int _CoursePriority;





        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", DbType = "Int NOT NULL")]

        public int Id
        {

            get
            {

                return this._Id;

            }

            set
            {

                if ((this._Id != value))
                {

                    this._Id = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseCode", DbType = "NVarChar(MAX)")]

        public string CourseCode
        {

            get
            {

                return this._CourseCode;

            }

            set
            {

                if ((this._CourseCode != value))
                {

                    this._CourseCode = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseName", DbType = "NVarChar(MAX)")]

        public string CourseName
        {

            get
            {

                return this._CourseName;

            }

            set
            {

                if ((this._CourseName != value))
                {

                    this._CourseName = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ShortDescription", DbType = "NVarChar(MAX)")]

        public string ShortDescription
        {

            get
            {

                return this._ShortDescription;

            }

            set
            {

                if ((this._ShortDescription != value))
                {

                    this._ShortDescription = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LongDescription", DbType = "NVarChar(MAX)")]

        public string LongDescription
        {

            get
            {

                return this._LongDescription;

            }

            set
            {

                if ((this._LongDescription != value))
                {

                    this._LongDescription = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Objective", DbType = "NVarChar(MAX)")]

        public string Objective
        {

            get
            {

                return this._Objective;

            }

            set
            {

                if ((this._Objective != value))
                {

                    this._Objective = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExamObjective", DbType = "NVarChar(MAX)")]

        public string ExamObjective
        {

            get
            {

                return this._ExamObjective;

            }

            set
            {

                if ((this._ExamObjective != value))
                {

                    this._ExamObjective = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EDXCourseLink", DbType = "NVarChar(MAX)")]

        public string EDXCourseLink
        {

            get
            {

                return this._EDXCourseLink;

            }

            set
            {

                if ((this._EDXCourseLink != value))
                {

                    this._EDXCourseLink = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StartDate", DbType = "DateTime")]

        public System.Nullable<System.DateTime> StartDate
        {

            get
            {

                return this._StartDate;

            }

            set
            {

                if ((this._StartDate != value))
                {

                    this._StartDate = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EndDate", DbType = "DateTime")]

        public System.Nullable<System.DateTime> EndDate
        {

            get
            {

                return this._EndDate;

            }

            set
            {

                if ((this._EndDate != value))
                {

                    this._EndDate = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreatedOn", DbType = "DateTime NOT NULL")]

        public System.DateTime CreatedOn
        {

            get
            {

                return this._CreatedOn;

            }

            set
            {

                if ((this._CreatedOn != value))
                {

                    this._CreatedOn = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreatedBy", DbType = "Int NOT NULL")]

        public int CreatedBy
        {

            get
            {

                return this._CreatedBy;

            }

            set
            {

                if ((this._CreatedBy != value))
                {

                    this._CreatedBy = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ModifiedOn", DbType = "DateTime NOT NULL")]

        public System.DateTime ModifiedOn
        {

            get
            {

                return this._ModifiedOn;

            }

            set
            {

                if ((this._ModifiedOn != value))
                {

                    this._ModifiedOn = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ModifiedBy", DbType = "Int NOT NULL")]

        public int ModifiedBy
        {

            get
            {

                return this._ModifiedBy;

            }

            set
            {

                if ((this._ModifiedBy != value))
                {

                    this._ModifiedBy = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseImageLink", DbType = "NVarChar(MAX)")]

        public string CourseImageLink
        {

            get
            {

                return this._CourseImageLink;

            }

            set
            {

                if ((this._CourseImageLink != value))
                {

                    this._CourseImageLink = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CertificationId", DbType = "Int")]

        public System.Nullable<int> CertificationId
        {

            get
            {

                return this._CertificationId;

            }

            set
            {

                if ((this._CertificationId != value))
                {

                    this._CertificationId = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BasePrice", DbType = "Decimal(18,2) NOT NULL")]

        public decimal BasePrice
        {

            get
            {

                return this._BasePrice;

            }

            set
            {

                if ((this._BasePrice != value))
                {

                    this._BasePrice = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LMSCourseId", DbType = "NVarChar(MAX)")]

        public string LMSCourseId
        {

            get
            {

                return this._LMSCourseId;

            }

            set
            {

                if ((this._LMSCourseId != value))
                {

                    this._LMSCourseId = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EnableForLMS", DbType = "Bit NOT NULL")]

        public bool EnableForLMS
        {

            get
            {

                return this._EnableForLMS;

            }

            set
            {

                if ((this._EnableForLMS != value))
                {

                    this._EnableForLMS = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EnableForCertification", DbType = "Bit NOT NULL")]

        public bool EnableForCertification
        {

            get
            {

                return this._EnableForCertification;

            }

            set
            {

                if ((this._EnableForCertification != value))
                {

                    this._EnableForCertification = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EnableForPayment", DbType = "Bit NOT NULL")]

        public bool EnableForPayment
        {

            get
            {

                return this._EnableForPayment;

            }

            set
            {

                if ((this._EnableForPayment != value))
                {

                    this._EnableForPayment = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Duration", DbType = "NVarChar(MAX)")]

        public string Duration
        {

            get
            {

                return this._Duration;

            }

            set
            {

                if ((this._Duration != value))
                {

                    this._Duration = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Hours", DbType = "Int NOT NULL")]

        public int Hours
        {

            get
            {

                return this._Hours;

            }

            set
            {

                if ((this._Hours != value))
                {

                    this._Hours = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NoOfSessions", DbType = "Int NOT NULL")]

        public int NoOfSessions
        {

            get
            {

                return this._NoOfSessions;

            }

            set
            {

                if ((this._NoOfSessions != value))
                {

                    this._NoOfSessions = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseAvailability", DbType = "Int NOT NULL")]

        public int CourseAvailability
        {

            get
            {

                return this._CourseAvailability;

            }

            set
            {

                if ((this._CourseAvailability != value))
                {

                    this._CourseAvailability = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseCategory", DbType = "NVarChar(MAX)")]

        public string CourseCategory
        {

            get
            {

                return this._CourseCategory;

            }

            set
            {

                if ((this._CourseCategory != value))
                {

                    this._CourseCategory = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseLevels", DbType = "Int NOT NULL")]

        public int CourseLevels
        {

            get
            {

                return this._CourseLevels;

            }

            set
            {

                if ((this._CourseLevels != value))
                {

                    this._CourseLevels = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseLanguage", DbType = "Int NOT NULL")]

        public int CourseLanguage
        {

            get
            {

                return this._CourseLanguage;

            }

            set
            {

                if ((this._CourseLanguage != value))
                {

                    this._CourseLanguage = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseTypes", DbType = "Int NOT NULL")]

        public int CourseTypes
        {

            get
            {

                return this._CourseTypes;

            }

            set
            {

                if ((this._CourseTypes != value))
                {

                    this._CourseTypes = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HasSampleContents", DbType = "Bit NOT NULL")]

        public bool HasSampleContents
        {

            get
            {

                return this._HasSampleContents;

            }

            set
            {

                if ((this._HasSampleContents != value))
                {

                    this._HasSampleContents = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SampleContentsLink", DbType = "NVarChar(MAX)")]

        public string SampleContentsLink
        {

            get
            {

                return this._SampleContentsLink;

            }

            set
            {

                if ((this._SampleContentsLink != value))
                {

                    this._SampleContentsLink = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreditPoints", DbType = "Int NOT NULL")]

        public int CreditPoints
        {

            get
            {

                return this._CreditPoints;

            }

            set
            {

                if ((this._CreditPoints != value))
                {

                    this._CreditPoints = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CertificationProvider", DbType = "Int")]

        public System.Nullable<int> CertificationProvider
        {

            get
            {

                return this._CertificationProvider;

            }

            set
            {

                if ((this._CertificationProvider != value))
                {

                    this._CertificationProvider = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExamManager", DbType = "Int")]

        public System.Nullable<int> ExamManager
        {

            get
            {

                return this._ExamManager;

            }

            set
            {

                if ((this._ExamManager != value))
                {

                    this._ExamManager = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CourseProvider", DbType = "Int")]

        public System.Nullable<int> CourseProvider
        {

            get
            {

                return this._CourseProvider;

            }

            set
            {

                if ((this._CourseProvider != value))
                {

                    this._CourseProvider = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HasVideoLink", DbType = "Bit NOT NULL")]

        public bool HasVideoLink
        {

            get
            {

                return this._HasVideoLink;

            }

            set
            {

                if ((this._HasVideoLink != value))
                {

                    this._HasVideoLink = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_VideoLink", DbType = "NVarChar(MAX)")]

        public string VideoLink
        {

            get
            {

                return this._VideoLink;

            }

            set
            {

                if ((this._VideoLink != value))
                {

                    this._VideoLink = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ScheduleApplicable", DbType = "Bit NOT NULL")]

        public bool ScheduleApplicable
        {

            get
            {

                return this._ScheduleApplicable;

            }

            set
            {

                if ((this._ScheduleApplicable != value))
                {

                    this._ScheduleApplicable = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DeliveryID", DbType = "Int NOT NULL")]

        public int DeliveryID
        {

            get
            {

                return this._DeliveryID;

            }

            set
            {

                if ((this._DeliveryID != value))
                {

                    this._DeliveryID = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Instructor", DbType = "NVarChar(MAX)")]

        public string Instructor
        {

            get
            {

                return this._Instructor;

            }

            set
            {

                if ((this._Instructor != value))
                {

                    this._Instructor = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Rating", DbType = "NVarChar(MAX)")]

        public string Rating
        {

            get
            {

                return this._Rating;

            }

            set
            {

                if ((this._Rating != value))
                {

                    this._Rating = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DisplayOnHomePage", DbType = "Bit NOT NULL")]

        public bool DisplayOnHomePage
        {

            get
            {

                return this._DisplayOnHomePage;

            }

            set
            {

                if ((this._DisplayOnHomePage != value))
                {

                    this._DisplayOnHomePage = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsActive", DbType = "Bit NOT NULL")]

        public bool IsActive
        {

            get
            {

                return this._IsActive;

            }

            set
            {

                if ((this._IsActive != value))
                {

                    this._IsActive = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EvidenceRequired", DbType = "Bit NOT NULL")]

        public bool EvidenceRequired
        {

            get
            {

                return this._EvidenceRequired;

            }

            set
            {

                if ((this._EvidenceRequired != value))
                {

                    this._EvidenceRequired = value;

                }

            }

        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CoursePriority", DbType = "Int NOT NULL")]

        public int CoursePriority
        {

            get
            {

                return this._CoursePriority;

            }

            set
            {

                if ((this._CoursePriority != value))
                {

                    this._CoursePriority = value;

                }

            }

        }

    }
    public partial class GetAllCourseDetailsResult
    {

        //[NotMapped]

        //public int? CoursePriority { get; set; }

        [NotMapped]

        public bool IsCourseEnrolled { get; set; }

        [NotMapped]

        public int CourseRatings { get; set; }

        [NotMapped]

        public string GoogleShareURL { get; set; }

        [NotMapped]

        public string GoogleCourseDescription { get; set; }

        [NotMapped]

        public string CategoryName { get; set; }

        [NotMapped]

        public string EmailCourseName { get; set; }

        // public int Id { get; set; }

        // public string CourseName { get; set; }

        //public decimal BasePrice { get; set; }

        //public string ShortDescription { get; set; }

        public string Category { get; set; }

        // public string CourseImageLink { get; set; }

        // public string Duration { get; set; }

        public string Availability { get; set; }

        //public DateTime CreatedOn { get; set; }

    }
}
#pragma warning restore 1591
